spring.application.name=matching

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

riot.api-key=${RIOT_API_KEY}
riot.regional-host=https://asia.api.riotgames.com
riot.platform-host=https://kr.api.riotgames.com
riot.season=2025

app.cors.allowed-origins=http://localhost:5173,http://localhost:5174,http://3.34.150.232:5173
